/* Static lesson text; keys are normalized Japanese source text. */
(function (root) {
  'use strict';
  const en = {
  "InfoQuantity Academy - 情報量の基礎学習ツール": "InfoQuantity Academy - An Introduction to Information Theory",
  "情報量とエントロピーの段階的学習システム。対数クイズから始まり、直感訓練、計算実習、理論確認、実世界応用まで体系的に学習。インタラクティブなグラフと計算器で I(a)=-log2 P(a) を完全理解。": "A step-by-step introduction to information and entropy: logarithm quizzes, probability predictions, calculations, theory, and applications. Explore I(a)=-log2 P(a) with interactive graphs and calculators.",
  "コンピューターサイエンスや数学に不慣れでも、「情報量」の直感と定義・性質を対話的に学べる入門ツールです": "An interactive introduction to information, its definition and properties, with no prior computer science background required.",
  "ライト／ダークを切り替える": "Switch light/dark theme",
  "1. 基礎知識": "1. Basics",
  "2. 情報量の定義": "2. Definition",
  "3. 体感": "3. Experience",
  "4. 計算例": "4. Examples",
  "5. 加算性": "5. Additivity",
  "6. 性質": "6. Properties",
  "7. エントロピー・応用": "7. Entropy & applications",
  "基礎知識：対数の理解度チェック": "Basics: check your understanding of logarithms",
  "🧩 対数クイズ": "🧩 Logarithm quiz",
  "情報量の学習には対数の基本的な理解が必要です。以下のクイズで確認してみましょう。": "Understanding information requires basic logarithms. Check your knowledge with these questions.",
  "問題1: log₂ 8 = ?": "Question 1: log₂ 8 = ?",
  "問題2: log₂ (1/4) = ?": "Question 2: log₂ (1/4) = ?",
  "問題3: 2ˣ = 16 のとき、x = ?": "Question 3: If 2ˣ = 16, what is x?",
  "正解数: 0/3": "Correct answers: 0/3",
  "リセット": "Reset",
  "📚 段階的導入：なぜ対数なのか？": "📚 Step by step: why logarithms?",
  "情報量の定義に対数が使われる理由を、段階的に理解していきましょう。": "Explore why logarithms appear in the definition of information.",
  "ステップ1: 「珍しさ」と「情報量」": "Step 1: rarity and information",
  "日常生活で考えてみると：": "Consider these examples:",
  "教材で雨の確率を30%と設定すると、雨が降ったときの情報量は約1.74bit": "If the teaching model assigns rain a probability of 30%, rain carries about 1.74 bit of information.",
  "教材で出来事の確率を0.001%と設定すると、情報量は約16.61bit": "An event assigned a probability of 0.001% carries about 16.61 bit of information.",
  "確実に起きるとモデルで仮定した出来事の情報量は0bit": "An event assumed certain in the model carries 0 bit of information.",
  "つまり、": "We define information so that ",
  "同じモデルで確率が低いほど情報量が大きい": "lower probability within the same model means more information",
  "と定義します。内容の重要性や感情的な驚きとは別の尺度です。": ". This is distinct from the importance of the content or emotional surprise.",
  "ステップ2: 独立事象の組み合わせ": "Step 2: combining independent events",
  "2つの独立した出来事が同時に起こる場合を考えてみましょう：": "Consider two independent events occurring together:",
  "コインで表が出る（1/2）+ サイコロで6が出る（1/6）": "Heads on a coin (1/2) + a 6 on a die (1/6)",
  "同時に起こる確率：1/2 × 1/6 = 1/12": "Joint probability: 1/2 × 1/6 = 1/12",
  "情報量に「足し算」を要求する：I(表) + I(6) = I(表かつ6)": "Require information to add: I(heads) + I(6) = I(heads and 6)",
  "確率は「掛け算」、情報量は「足し算」になるような関数が必要です。": "We need a function that turns multiplication of probabilities into addition of information.",
  "ステップ3: 対数の性質": "Step 3: a property of logarithms",
  "対数には重要な性質があります：": "Logarithms have this useful property:",
  "これで確率の積→情報量の和に変換できます": "This converts a product of probabilities into a sum of information.",
  "だから情報量は": "This gives the form ",
  "の形になるのです！": " for information.",
  "🎯 学習の進め方": "🎯 How to study",
  "対数クイズで基礎確認": "Check your logarithms",
  "- 上記クイズで3問中2問以上正解を目指しましょう": " - Aim to answer at least two of the three questions correctly.",
  "定義の理解": "Understand the definition",
  "- 次のタブで情報量の正式な定義を学習": " - Learn the formal definition in the next tab.",
  "体感的理解": "Build intuition",
  "- 「体感」タブで驚きと情報量の関係を実感": " - Explore surprise and information in the Experience tab.",
  "計算練習": "Practice calculations",
  "- 「計算例」タブで具体的な計算に慣れる": " - Work through specific probabilities in the Examples tab.",
  "理論の深化": "Explore the theory",
  "- 加算性、性質を理解": " - Understand additivity and the other properties.",
  "応用展開": "Explore applications",
  "- 実世界での活用例を知る": " - See uses in the real world.",
  "情報量の定義": "Definition of information",
  "🌟 豊富な直感例": "🌟 Intuitive examples",
  "📰 ニュース・メディア": "📰 News & media",
  "ニュースのたとえ": "A news analogy",
  "：「犬が人を噛んでもニュースにならないが、人が犬を噛んだらニュースになる」→ めったに起きないほど情報量が大きい": ": a dog biting a person may not be news, but a person biting a dog is unusual. Rarer events carry more information.",
  "スポーツ": "Sports",
  "：教材で「王者が勝利」を70%、「大番狂わせ」を5%と設定すると、後者の情報量が大きい": ": in a teaching model assigning 70% to the champion winning and 5% to an upset, the latter carries more information.",
  "芸能": "Entertainment",
  "：「人気俳優の結婚発表」→ 予想外度が高いほど話題性が大きい": ": an unexpected celebrity marriage announcement may attract more attention.",
  "🎲 ゲーム・確率": "🎲 Games & probability",
  "コイン投げ": "Coin",
  "：「表が出た」(50%) より「立った」(0.01%) はまれ → 情報量が大きい": ": landing on its edge (0.01%) is rarer than heads (50%), so it carries more information in this model.",
  "サイコロ": "Die",
  "：「1が出た」(1/6) より「連続で6回とも1の目」(1/6⁶) → 後者は驚異的": ": rolling a 1 six times (1/6⁶) is much rarer than rolling a 1 once (1/6).",
  "宝くじ": "Lottery",
  "：「はずれ」は当たり前、「1等当選」は人生を変える情報": ": no prize is common, while a top prize may be life-changing.",
  "🌤️ 日常生活": "🌤️ Everyday life",
  "天気": "Weather",
  "：「晴れの日に雨」→ 予報が外れると情報価値が高い": ": rain on a predicted sunny day is unexpected.",
  "交通": "Transport",
  "：「電車が定刻」は当然、「大幅遅延」は重要情報": ": a train on time is expected; a major delay may be important.",
  "メール": "Email",
  "：「スパム」vs「重要な連絡」→ 情報量は、モデルでの確率の逆数の対数": ": spam versus an important message. Information is the logarithm of the reciprocal of the model probability.",
  "💡 学習・発見": "💡 Learning & discovery",
  "試験結果": "Exam results",
  "：「予想通りの点数」vs「予想外の高得点/低得点」": ": expected scores versus unexpectedly high or low scores.",
  "科学的発見": "Scientific discovery",
  "：「既知の法則通り」vs「新しい現象の発見」": ": known laws versus a new phenomenon.",
  "AI予測": "AI predictions",
  "：「高確信度の予測」vs「低確信度だが的中」→ 設定した確率が低いほど情報量が大きい": ": high-confidence versus low-confidence correct predictions. A lower assigned probability gives more information.",
  "🔑 重要な洞察": "🔑 A key distinction",
  "情報の価値 ≠ 情報量": "Value of information ≠ information quantity",
  "：受け手にとっての「価値」と、確率にもとづく「情報量」は区別して考える必要があります。情報量は選んだ確率モデルから計算する尺度で、価値とは別です。例の確率は教材用の設定値です。": ": personal value and probability-based information are different. Information is calculated from a chosen probability model. The probabilities here are teaching assumptions.",
  "シャノンの定義": "Shannon's definition",
  "事象": "For event ",
  "の生起確率を": ", let its probability be ",
  "とすると、情報量": ". Define its information ",
  "を": " as ",
  "と定義する（単位：bit）。": " (unit: bit).",
  "非負": "Nonnegative",
  "なので": " implies ",
  "単調減少": "Monotonically decreasing",
  "：めったに起きないほど値が大きい": ": rarer events have larger values.",
  "P=1でI=0": "I=0 at P=1",
  "：確実な事象は情報量ゼロ": ": a certain event carries zero information.",
  "I = -log₂ P のグラフ": "Graph of I = -log₂ P",
  "横軸: P (0<P≤1), 縦軸: I=-log₂P。上限16bitを超える部分は枠外です。": "Horizontal: P (0<P≤1). Vertical: I=-log₂P. Values above 16 bit lie outside the plot.",
  "📊 このグラフの見方": "📊 Reading the graph",
  "曲線の特徴": "Shape of the curve",
  "：確率が小さいほど情報量が急激に増加": ": information increases steeply as probability decreases.",
  "重要なポイント": "Key points",
  "：P=0.5で1bit、P=0.25で2bit、P=0.125で3bit": ": P=0.5 gives 1 bit, P=0.25 gives 2 bit, and P=0.125 gives 3 bit.",
  "実感のコツ": "Building intuition",
  "：確率が半分になるたび情報量が1bit増える": ": halving probability adds 1 bit of information.",
  "比較：y=a": "Comparison: y=a",
  "底 a を選択:": "Choose the base a:",
  "🔧 操作方法": "🔧 Controls",
  "底aを変更": "Change the base a",
  "して3つの関数の関係性を比較できます。": " to compare the three functions.",
  "指数関数（青）": "Exponential (blue)",
  "：急激に増加、y=aˣ": ": rapid growth, y=aˣ.",
  "一次関数（黄）": "Linear (yellow)",
  "：直線的増加、比例関係": ": proportional, straight-line growth.",
  "対数関数（水色）": "Logarithmic (cyan)",
  "：緩やかに増加、y=logₐx": ": slower growth, y=logₐx.",
  "a>1のとき、指数と対数は互いに逆関数です。表示範囲の外側は省略しています。": "For a>1, exponentiation and logarithms are inverse functions. Parts outside the plotted range are omitted.",
  "体感：驚きと情報量の関係": "Experience: surprise and information",
  "🎲 驚き度体感スライダー": "🎲 Subjective surprise slider",
  "使い方": "Instructions",
  "：①シナリオ選択 → ②出来事選択 → ③驚き度と予想確率を入力 → ④設定値と比較": ": ① Select a scenario → ② Select an event → ③ Enter surprise and predicted probability → ④ Compare with the model",
  "①シナリオを選択:": "① Choose a scenario:",
  "天気予報": "Weather forecast",
  "②出来事を選択:": "② Choose an event:",
  "表が出た": "Heads",
  "裏が出た": "Tails",
  "立った": "Lands on its edge",
  "割れた": "Breaks",
  "各選択肢は個別の出来事です。互いに重なる場合があり、一覧全体で確率分布を表すものではありません。": "Each option describes an individual event. Events may overlap; the whole list is not a probability distribution.",
  "③この結果にどのくらい驚きますか？": "③ How surprising would this outcome be?",
  "驚き度（1: 全然驚かない ～ 10: 超驚く）": "Surprise (1: not surprising — 10: very surprising)",
  "あなたの驚き度:": "Your surprise:",
  "この出来事の確率はどのくらいだと思いますか？": "What probability would you assign to this event?",
  "確率予想（%）": "Predicted probability (%)",
  "④設定値と比較する": "④ Compare with the model",
  "教材の設定確率": "Model probability",
  "設定確率からの情報量": "Information from the model probability",
  "予想確率からの情報量": "Information from your prediction",
  "予想確率と設定確率を比較します。驚き度は採点しません。": "Compare your prediction with the model. Subjective surprise is not scored.",
  "💡 効果的な使い方": "💡 Study tips",
  "極端な例を試す": "Try contrasting examples",
  "：教材用の「特賞」と「コインの表」で驚き度の違いを記録": ": record how a top prize in the teaching model and heads on a coin feel different",
  "予想してから確認": "Predict before comparing",
  "：確率を予想してから設定値を確認。驚き度は採点しません": ": predict the probability before checking the model. Subjective surprise is not scored",
  "データを蓄積": "Collect observations",
  "：「現在の値を記録」でグラフに点をプロット、傾向を可視化": ": record the current values to plot points and observe patterns.",
  "対数感覚の訓練": "Develop a sense of logarithms",
  "：確率が半分になるたび情報量+1bitの感覚を身につける": ": each halving of probability adds 1 bit.",
  "📊 直感と理論の比較グラフ": "📊 Subjective surprise and model information",
  "主観の驚き度と、教材の設定確率から計算した情報量を記録します。正解の線や採点はありません。": "Record your subjective surprise and the information calculated from the model probability. There is no correct line or score.",
  "🎯 使い方チュートリアル": "🎯 Walkthrough",
  "様々なシナリオを試す": "Try different scenarios",
  "コイン、サイコロ、宝くじなど異なる確率の出来事で驚き度を設定": "Set your surprise for events with different probabilities, such as coins, dice, and lotteries.",
  "「現在の値を記録」をクリック": "Click Record current values",
  "あなたの驚き度と理論値がグラフ上に点として記録される": "Your surprise and the model information are recorded as a point.",
  "パターンを観察": "Observe patterns",
  "横軸は主観の驚き度、縦軸は設定確率からの情報量": "Horizontal: subjective surprise. Vertical: information from the model probability.",
  "記録を比較": "Compare records",
  "同じ確率でも出来事によって感じ方が違うかを観察": "Observe whether different events feel different even at the same probability",
  "記録した出来事": "Recorded events",
  "現在の値を記録": "Record current values",
  "データクリア": "Clear records",
  "記録点数:": "Records:",
  "📖 グラフの読み方": "📖 Reading the graph",
  "横軸の意味": "Horizontal axis",
  "主観の驚き度を1～10で記録": "Record subjective surprise from 1 to 10",
  "他の人と同じ値にする必要はありません": "Your ratings do not have to match anyone else's",
  "縦軸の意味": "Vertical axis",
  "設定確率が小さいほど情報量が大きい": "A lower assigned probability gives more information",
  "縦軸は有限値に合わせて広がります": "The vertical scale expands to fit finite values",
  "確率0の記録": "Records with probability 0",
  "∞はグラフの点に変換しません": "Infinity is not converted into a graph point",
  "記録一覧に∞のまま残します": "It remains ∞ in the record list",
  "💡 実践のコツ": "💡 Practice tips",
  "異なる出来事を比べる": "Start with contrasting examples",
  "：確実な事象と、まれな事象で感じ方を記録": ": compare a certain event with a very unlikely event",
  "中間の例も記録": "Explore intermediate examples",
  "：それぞれの出来事をどれほど驚くと感じたかを記録": ": record how surprising each event feels to you",
  "確率と感情を分ける": "Separate probability from feelings",
  "：同じ確率でも同じ驚き度にする必要はありません": ": equally likely events need not feel equally surprising",
  "記録を振り返る": "Review your records",
  "：予想確率と教材の設定確率を比較": ": compare your probability predictions with the assigned probabilities",
  "🧠 体感のコツ": "🧠 Developing intuition",
  "珍しさと情報量": "Rarity and information",
  "：同じモデルで確率が低いほど情報量が大きい": ": within the same model, lower probability means more information",
  "予想外度 = 驚き": "Unexpectedness and surprise",
  "：期待していなかったほど驚く": ": unexpected events can feel surprising",
  "対数的感覚": "A logarithmic scale",
  "：確率が1/2→1/4→1/8と半分になるたび、情報量は1bitずつ増加": ": each halving of probability, from 1/2 to 1/4 to 1/8, adds 1 bit",
  "日常の感覚": "Everyday feelings",
  "：感情的な驚きと、確率から計算した情報量を区別": ": distinguish emotional surprise from information calculated from probability",
  "練習例": "Practice examples",
  "雨が降る": "Rain",
  "確率30% → 1.74 bit": "Probability 30% → 1.74 bit",
  "確率は教材用の設定": "Probabilities are assigned for this lesson",
  "雪が降る（夏）": "Snow in summer",
  "確率0.01% → 13.29 bit": "Probability 0.01% → 13.29 bit",
  "実際の気象データではない": "These are not actual weather data",
  "太陽が昇る": "The sun rises",
  "確率99.99% → 0.0001 bit": "Probability 99.99% → 0.0001 bit",
  "驚きの感じ方は人によって異なる": "People experience surprise differently",
  "コイン投げの情報量": "Information in a coin toss",
  "確率の入力": "Enter probabilities",
  "事象定義： a₀ = 表、a₁ = 裏、a₂ = 立つ、a₃ = 割れる": "Events: a₀ = heads, a₁ = tails, a₂ = lands on its edge, a₃ = breaks",
  "プリセット例（クリックで自動入力）：": "Presets (click to fill in values):",
  "通常のコイン": "Fair coin",
  "偏ったコイン": "Biased coin",
  "イカサマ（両面表）": "Trick coin (two heads)",
  "立つ確率 1/10000": "Edge probability 1/10000",
  "合計 P =": "Total P =",
  "※ 合計が 1 ではありません": "※ The total is not 1",
  "🧮 計算器の使い方": "🧮 Using the calculator",
  "確率入力": "Probability inputs",
  "：各事象の確率を0～1の範囲で設定（合計1になるよう調整）": ": enter each event's probability from 0 to 1, with a total of 1",
  "プリセット利用": "Use presets",
  "：「通常のコイン」「偏ったコイン」等のボタンで典型例を素早く設定": ": quickly load examples such as a fair or biased coin",
  "計算結果": "Calculation results",
  "：各ボックスにリアルタイムで情報量が表示、計算過程も確認可能": ": each box updates immediately and shows the calculation",
  "比較分析": "Compare results",
  "：異なる確率での情報量を同時比較し、パターンを理解": ": compare information at different probabilities to understand the pattern",
  "📝 練習問題": "📝 Exercises",
  "問題1: 基本計算": "Exercise 1: Basic calculation",
  "確率 P = 1/8 の事象が起きたとき、情報量 I は何bitか？": "How many bits of information does an event with P = 1/8 provide?",
  "答えを見る": "Show answer",
  "答え: 3 bit": "Answer: 3 bit",
  "問題2: 現実的なシナリオ": "Exercise 2: A practical scenario",
  "天気予報で「明日雨が降る確率70%」と発表された。実際に雨が降った場合と降らなかった場合、それぞれの情報量は？": "A forecast assigns a 70% probability to rain tomorrow. How much information is obtained if it rains, and if it does not?",
  "雨が降った場合": "If it rains",
  "雨が降らなかった場合": "If it does not rain",
  "予想外だった「降らなかった」方が情報量が大きい！": "The less expected outcome, no rain, provides more information.",
  "問題3: 情報量の比較": "Exercise 3: Compare information",
  "以下の出来事を情報量の大きい順に並べよ：": "Order these events from most to least information:",
  "A) 公正なコインで表が出る (P=0.5)": "A) Heads on a fair coin (P=0.5)",
  "B) サイコロで1が出る (P=1/6)": "B) Rolling a 1 on a fair die (P=1/6)",
  "C) 教材用のくじで特賞 (P=2×10⁻⁸)": "C) Top prize in a teaching example (P=2×10⁻⁸)",
  "答え: C > B > A": "Answer: C > B > A",
  "教材用の特賞は情報量が大きい例です。": "The top-prize example provides much more information.",
  "問題4: 実践計算": "Exercise 4: Calculate it yourself",
  "上記の計算器を使って、以下のシナリオの情報量を求めよ：": "Use the calculator above to find the information in this scenario:",
  "「偏ったコイン」プリセット → a₂（立つ）の情報量は？": "Load the biased-coin preset. How much information does a₂ (landing on its edge) provide?",
  "ヒント": "Hint",
  "プリセットボタンを押して、P(a₂)の値を確認してから計算しましょう。": "Click the preset, check P(a₂), and then calculate.",
  "補足": "Notes",
  "P=0 のとき": "When P=0,",
  "は未定義だが、理論上": "is undefined, but in the limiting sense,",
  "（不可能事象が起きた＝モデル破綻）。UIでは「∞ bit」と表示。": "(an impossible event would contradict the model). The interface displays “∞ bit.”",
  "受け手の主観による「価値」と、確率にもとづく「情報量」は区別して考える。": "Distinguish subjective value to a recipient from information based on probability.",
  "加算性：独立事象が同時に起きたときの情報量": "Additivity: information from independent events occurring together",
  "なぜ I(a) = -log₂ P(a) なのか": "Why is I(a) = -log₂ P(a)?",
  "情報量の定義がこの形になる理由の一つは、": "One reason for this definition of information is that it",
  "加算性を満たす": "satisfies additivity",
  "ためです。": ".",
  "独立事象 A, B が同時に起きたとき：": "When independent events A and B both occur:",
  "確率は積：P(A∧B) = P(A) × P(B)": "Their probabilities multiply: P(A∧B) = P(A) × P(B)",
  "情報量は和：I(A∧B) = I(A) + I(B)": "Their information adds: I(A∧B) = I(A) + I(B)",
  "単調性も仮定すると、この関係を満たす関数は対数関数": "With monotonicity, a function satisfying this relationship must have the logarithmic form",
  "の形に限られます（定数倍を除く）。": "(up to a constant factor).",
  "「独立な情報の組み合わせは、それぞれの情報量の足し算になる」": "“Combining independent information adds the individual information values”",
  "という自然な要請から、シャノンの定義が導かれるのです。": "is a natural requirement leading to Shannon's definition.",
  "一般の独立事象 A, B": "General independent events A and B",
  "例：マンションの部屋特定": "Example: identifying an apartment",
  "階数（例: 16）": "Number of floors (e.g. 16)",
  "各階の部屋数（例: 8）": "Rooms per floor (e.g. 8)",
  "I(階の特定)": "I(identifying the floor)",
  "I(号室の特定)": "I(identifying the room on a floor)",
  "I(部屋番号の特定)": "I(identifying the apartment)",
  "情報量が満たすべき性質": "Properties of information",
  "🔻 単調減少性（Monotonicity）": "🔻 Monotonicity",
  "確率が大きいほど情報量は小さく、確率が小さいほど情報量は大きい。": "Higher probability means less information; lower probability means more information.",
  "P を動かして確認:": "Adjust P:",
  "現在 P =": "Current P =",
  "現在の点": "Current point",
  "：スライダーで動かした確率とその情報量": ": the selected probability and its information",
  "曲線全体": "Entire curve",
  "：右に行くほど（確率↑）情報量は下がる": ": information decreases to the right as probability increases",
  "💡 身近な例で理解": "💡 Familiar examples",
  "確実な事象": "Certain event",
  "「太陽が昇る」": "“The sun rises”",
  "普通の事象": "Ordinary event",
  "「コインで表」": "“Heads on a coin toss”",
  "稀な事象": "Rare event",
  "「100分の1の確率」": "“A 1-in-100 event”",
  "極稀な事象": "Extremely rare event",
  "「宝くじレベル」": "“A lottery-like event”",
  "⚡ 連続性（Continuity）": "⚡ Continuity",
  "0<P≤1の各点で連続です。ただしPが0に近いほど変化率は大きく、確率差だけから情報量差の大小は決まりません。": "The function is continuous at every point with 0<P≤1. Its rate of change grows near 0, so probability differences alone do not determine information differences.",
  "確率差：|P₂ - P₁| =": "Probability difference: |P₂ - P₁| =",
  "情報量差：|I₂ - I₁| =": "Information difference: |I₂ - I₁| =",
  "🔧 連続性の確認方法": "🔧 Exploring continuity",
  "0.5と0.51、0.0001と0.0101を比べてください。確率差が同じでも情報量差は異なります。": "Compare 0.5 with 0.51, and 0.0001 with 0.0101. Equal probability differences can produce different information differences.",
  "➕ 加法性（Additivity）": "➕ Additivity",
  "独立事象A, Bについて、I(A∧B) = I(A) + I(B) が成り立つ。": "For independent events A and B, I(A∧B) = I(A) + I(B).",
  "🎲 実例：サイコロ＋コイン": "🎲 Example: die and coin",
  "事象A：サイコロで6が出る": "Event A: rolling a 6 on a fair die",
  "事象B：コインで表が出る": "Event B: heads on a fair coin",
  "事象A∧B：両方同時に起こる": "Event A∧B: both occur",
  "検証：I(A) + I(B) =": "Check: I(A) + I(B) =",
  "🔧 カスタム検証": "🔧 Try your own values",
  "📏 規格化（Normalization）": "📏 Normalization",
  "基準を決めることでスケールが定まる。通常「P=1/2の事象の情報量を1bit」とする。": "Choosing a reference fixes the scale. The usual convention assigns 1 bit to an event with P=1/2.",
  "🎯 異なる基準での比較": "🎯 Compare logarithm bases",
  "情報量の基準を選択:": "Choose the information unit:",
  "2進法（bit）：log₂": "Base 2 (bit): log₂",
  "自然対数（nat）：ln": "Natural logarithm (nat): ln",
  "10進法（dit）：log₁₀": "Base 10 (dit): log₁₀",
  "P = 1/2 の情報量": "Information for P = 1/2",
  "P = 1/4 の情報量": "Information for P = 1/4",
  "P = 1/10 の情報量": "Information for P = 1/10",
  "重要": "Important",
  "：基準が変わっても相対的な関係は保たれます。P=1/4の情報量は常にP=1/2の2倍です。": ": changing the base preserves relative relationships. Information at P=1/4 is always twice that at P=1/2.",
  "エントロピー・応用：平均情報量と実世界での活用": "Entropy and applications: average information and real-world uses",
  "📊 エントロピー（平均情報量）の定義": "📊 Definition of entropy (average information)",
  "情報源 X の": "For an information source X, entropy is the",
  "平均的に得られる情報量": "average information obtained",
  "（期待値）であり、": "(the expected value) and measures",
  "分布の不確定さ": "uncertainty in the distribution",
  "の尺度：": ":",
  "均等分布ほど不確定さが大きい → エントロピーが大きい": "A uniform distribution has greater uncertainty and higher entropy",
  "確実（1つに集中）なら不確定さがない → エントロピー 0": "A certain outcome (all probability on one event) has no uncertainty: entropy is 0",
  "エントロピー計算器（最大4事象）": "Entropy calculator (up to 4 events)",
  "エントロピー H(X)": "Entropy H(X)",
  "均等：H が最大（例：4事象なら 2 bit）": "Uniform: maximum H (e.g. 2 bit for 4 events)",
  "集中：H が小さい（極端には 0）": "Concentrated: smaller H (down to 0)",
  "⚙️ エントロピー計算器の使い方": "⚙️ Using the entropy calculator",
  "確率分布の設定": "Set a probability distribution",
  "：4つまでの事象について確率を設定（合計1）": ": enter probabilities for up to 4 events, totaling 1",
  "リアルタイム計算": "Live calculation",
  "：入力と同時にエントロピーと計算過程を表示": ": entropy and calculation steps update as you type",
  "分布の比較": "Compare distributions",
  "：均等分布（0.25, 0.25, 0.25, 0.25）vs 偏った分布（0.7, 0.2, 0.1, 0）で違いを実感": ": compare a uniform distribution (0.25, 0.25, 0.25, 0.25) with a biased one (0.7, 0.2, 0.1, 0)",
  "応用理解": "Explore applications",
  "：データ圧縮や暗号強度の理論的基盤を数値で体感": ": examine the theoretical foundations of compression and cryptographic strength numerically",
  "🛡️ エントロピーと攻撃の関係": "🛡️ Entropy and attacks",
  "N個の候補が等確率で、重複なく1個ずつ試して正解を判別できるモデルでは、H=log₂N、平均試行回数=(N+1)/2です。": "In a model with N equally likely candidates, tested one at a time without repetition and with a recognizable correct answer, H=log₂N and the average number of trials is (N+1)/2.",
  "一般の偏った分布では、Shannonエントロピーだけから平均試行回数は決まりません。攻撃時間には方式と1秒あたりの試行回数などの条件も必要です。": "For a general biased distribution, Shannon entropy alone does not determine the average number of guesses. Attack time also depends on the method, trial rate, and other conditions.",
  "💾 データ圧縮の原理": "💾 Principles of data compression",
  "情報量とエントロピーは、データ圧縮の理論的基盤です。": "Information and entropy provide the theoretical foundations of data compression.",
  "教材用の1000文字から一部を抜粋した例": "Selected characters from a teaching example of 1000 characters",
  "文字": "Character",
  "頻度": "Frequency",
  "確率": "Probability",
  "情報量": "Information",
  "⌈情報量⌉の例": "Example of ⌈information⌉",
  "原理": "Principle",
  "：頻出文字ほど短い符号、稀な文字ほど長い符号を割り当てることで、全体の平均符号長を最小化。": ": assigning shorter codes to frequent characters and longer codes to rare ones can minimize average code length.",
  "理論限界": "Theoretical bound",
  "：離散情報源の一意復号可能な符号では平均符号長 ≥ エントロピー。表は完全な分布やHuffman符号の割り当てではありません。": ": for a uniquely decodable code of a discrete source, average code length ≥ entropy. This table is neither a complete distribution nor a Huffman code assignment.",
  "身近な圧縮技術": "Familiar compression techniques",
  "ZIPのDEFLATE": "ZIP's DEFLATE",
  "：LZ77 + Huffman符号": ": LZ77 + Huffman coding",
  "：DCT変換 + 量子化 + エントロピー符号化": ": DCT + quantization + entropy coding",
  "：心理音響モデル + 適応的量子化": ": psychoacoustic modeling + adaptive quantization",
  "言語モデル": "Language models",
  "：正解トークンの予測確率を高めるクロスエントロピー損失を利用": ": use cross-entropy loss to increase the predicted probability of the correct token",
  "🔐 暗号学での情報量": "🔐 Information in cryptography",
  "鍵の不確実性と、暗号を破るための計算量は異なります。エントロピーだけでは暗号方式や実装の安全性を判定できません。": "Key uncertainty and the computational cost of breaking a cipher are different. Entropy alone cannot establish the security of a cryptographic scheme or implementation.",
  "一様ランダムな文字列のモデル": "Model of a uniformly random string",
  "パスワード文字数:": "Password length:",
  "文字種類数:": "Alphabet size:",
  "エントロピー:": "Entropy:",
  "推測回数:": "Guesses:",
  "1.5 × 10¹⁴ 回": "1.5 × 10¹⁴ trials",
  "前提:": "Assumptions:",
  "🔐 文字列モデルの使い方": "🔐 Using the string model",
  "文字数": "Length",
  "：パスワードの長さを設定": ": set the password length",
  "文字種類数": "Alphabet size",
  "：使用可能文字の総数（空白を含む印字可能ASCII文字=95、英数字=62等）": ": total available characters (e.g. 95 printable ASCII characters including space, or 62 letters and digits)",
  "エントロピー": "Entropy",
  "：各文字を独立に等確率で選ぶと仮定した不確実性": ": uncertainty assuming each character is selected independently and uniformly",
  "推測回数": "Guesses",
  "：候補を重複なく試し、正解を判別できる場合の平均(N+1)/2": ": average (N+1)/2 when candidates are tried without repetition and the correct answer can be recognized",
  "人が選んだ単語、再利用、偏りは評価しません。文字列そのものを入力する機能はありません。": "Human-chosen words, reuse, and selection biases are not assessed. The tool does not accept an actual password.",
  "暗号アルゴリズム比較": "Comparison of cryptographic algorithms",
  "方式": "Scheme",
  "鍵長": "Key size",
  "古典計算での安全強度の目安": "Approximate security strength against classical computation",
  "破綻済み": "Broken",
  "NIST SP 800-57 Part 1 Rev.5の比較値です。安全性の保証や量子計算への耐性を示す表ではありません。": "Comparison values are from NIST SP 800-57 Part 1 Rev.5. This table is neither a security guarantee nor an assessment of resistance to quantum computation.",
  "完全秘匿性（Perfect Secrecy）": "Perfect secrecy",
  "シャノンが証明した理想的暗号の条件：": "Conditions for ideal secrecy established by Shannon:",
  "H(平文|暗号文) = H(平文)": "H(plaintext|ciphertext) = H(plaintext)",
  "：暗号文から平文への情報漏洩ゼロ": ": the ciphertext reveals no information about the plaintext",
  "鍵エントロピー ≥ 平文エントロピー": "Key entropy ≥ plaintext entropy",
  "：十分なランダムネス必要": ": sufficient randomness is required",
  "ワンタイムパッド": "One-time pad",
  "：平文と独立な一様ランダムの鍵を平文と同じ長さだけ用意し、再利用しない場合の例。改ざんを検知する機能は別途必要": ": an example when a uniformly random key, independent of the plaintext and equally long, is never reused. Tamper detection requires a separate mechanism",
  "🌡️ 物理学のエントロピーとの関係": "🌡️ Relationship to thermodynamic entropy",
  "情報エントロピーと熱力学エントロピーは深い関係があります。": "Information entropy and thermodynamic entropy are closely related.",
  "共通点": "Similarities",
  "不確実性の尺度": "A measure of uncertainty",
  "：確率分布を使った記述ができる": ": can be described using probability distributions",
  "対数的構造": "Logarithmic structure",
  "加法性": "Additivity",
  "：独立系では和で表現": ": independent systems can be expressed as a sum",
  "注意": "Caution",
  "：情報エントロピーが時間とともに必ず増えるという法則はない": ": there is no law that information entropy must always increase over time",
  "相違点": "Differences",
  "対象": "Subject",
  "：情報 vs 物理系": ": information versus physical systems",
  "単位": "Units",
  "物理系": "Physical systems",
  "：可逆過程と不可逆過程の区別が必要": ": reversible and irreversible processes must be distinguished",
  "前提": "Assumptions",
  "：確率モデルと物理状態の対応を指定する必要がある": ": the correspondence between the probability model and physical states must be specified",
  "マクスウェルの悪魔": "Maxwell's demon",
  "情報と物理エントロピーの関係を示す思考実験：": "A thought experiment about information and physical entropy:",
  "悪魔が分子の運動を「観測」して仕分け": "A demon observes molecular motion and sorts molecules",
  "観測で「情報」を得る → エントロピー減少？": "Observation obtains information: does entropy decrease?",
  "測定そのものに一定の散逸が必須とは限らない。記憶の消去を含めて考える": "Measurement itself does not necessarily require a fixed amount of dissipation. Memory erasure must also be considered",
  "結論": "Conclusion",
  "：標準的な熱浴モデルでは、0と1が等確率の未知の1bitを論理的に不可逆に消去する散逸の下限はkBT ln2": ": in a standard heat-bath model, logically irreversible erasure of an unknown unbiased bit has a minimum dissipation of kBT ln2",
  "🤖 機械学習・AI での活用": "🤖 Applications in machine learning and AI",
  "現代AIの多くの技術で情報量が中心的役割を果たしています。": "Information plays a central role in many modern AI techniques.",
  "決定木の分岐基準": "Splitting criteria for decision trees",
  "情報利得": "Information gain",
  "= H(全体) - 分割後の各群のHの重み付き平均": "= H(all samples) - weighted average of H for the groups after a split",
  "最も不確実性を減らす特徴量で分岐": "Split on the feature that reduces uncertainty most",
  "言語モデル（GPT等）": "Language models (e.g. GPT)",
  "クロスエントロピー損失": "Cross-entropy loss",
  "で学習": "is used for training",
  "次の単語の確率分布を最適化": "Optimize the probability distribution of the next token",
  "変分オートエンコーダー": "Variational autoencoders",
  "KLダイバージェンス": "KL divergence",
  "で正則化": "is used for regularization",
  "情報のボトルネック効果を利用": "Use an information bottleneck effect",
  "強化学習": "Reinforcement learning",
  "エントロピー正則化": "Entropy regularization",
  "で探索促進": "encourages exploration",
  "不確実性を保つことで局所解回避": "Maintain uncertainty to help avoid local optima",
  "情報ボトルネック理論": "Information bottleneck theory",
  "入力Xの表現Tに、目標Yの予測に必要な情報を残すという設計上の考え方です。すべての深層学習が次の段階を通るという意味ではありません。": "A design principle that keeps information needed to predict target Y in a representation T of input X. It does not mean that all deep learning passes through the following stages.",
  "圧縮の目的": "Compression objective",
  "：I(X;T)を最小化（入力の冗長性除去）": ": minimize I(X;T) (remove redundant input information)",
  "予測の目的": "Prediction objective",
  "：I(T;Y)を最大化（出力との相関強化）": ": maximize I(T;Y) (retain information about the output)",
  "最適解": "Optimal solution",
  "：圧縮と予測のトレードオフ": ": a trade-off between compression and prediction",
  "🔬 その他の応用分野": "🔬 Other application areas",
  "🧬 生物学・遺伝学": "🧬 Biology and genetics",
  "DNA配列の情報量解析": "Information analysis of DNA sequences",
  "タンパク質構造の予測": "Protein structure prediction",
  "進化の情報理論的モデル": "Information-theoretic models of evolution",
  "📊 統計学・データサイエンス": "📊 Statistics and data science",
  "相互情報量による特徴選択": "Feature selection using mutual information",
  "異常検知アルゴリズム": "Anomaly detection algorithms",
  "因果推論の情報理論的手法": "Information-theoretic approaches to causal inference",
  "📡 通信工学": "📡 Communications engineering",
  "チャネル容量の計算": "Channel capacity calculations",
  "誤り訂正符号の設計": "Error-correcting code design",
  "5G/6Gの効率化技術": "Techniques for efficient 5G/6G communications",
  "🧠 認知科学・心理学": "🧠 Cognitive science and psychology",
  "人間の情報処理能力測定": "Measuring human information-processing capacity",
  "学習効率の最適化": "Optimizing learning efficiency",
  "意思決定の情報理論的分析": "Information-theoretic analysis of decision-making",
  "🔗 GitHubリポジトリーはこちら（": "🔗 GitHub repository ("
};
  if (typeof module === 'object' && module.exports) module.exports = en;
  else root.InfoLessonEnglish = en;
})(globalThis);
